language: node_js
node_js:
- node
deploy:
  provider: npm
  skip_cleanup: true
  email: nicolas.vanhoren@gmail.com
  api_key:
    secure: H/SoroxyjmsFTrHA4aa5ikVa3TqzLM8RYvS4bJm4o0n2fByXDL9da1PkYvnJgYze9XOjQxqAaPIEaZASVzfdCyT3u8uWIbiy6XCOJWoRDN3dKxhP9mNt3uWgS3KD2/HURi6MwsStYxQAxzatvulTb8myKHe99CIUNrsQ7/B0jZwsWywboQPhwESNgkby995QE1wG4o1JkmkoBot1P+NyoOE1UBJ3xnTfOd4TVLXgbbDzt73DYKS7998sQzSNW8p2ldsL1p4dOo0R/FoNXdObT3gfXd1tmfjbATyF3cY5RtEdHoi1g+dFtajeE33Rju+zOkIOYhZH/z52YCH+dSZUE/6B/0UpR9BXBlu7nlBvQufE0U/YOG88t0ng5ZTvMinT/iKtiIsEKmCyBe451tKkhNm1bWoPnGOXbG30QLfvKXy5yUIe4j/0oMxq8ibH08JpoImR6CWVv1oI0MJO8ZxE1cRJQlAP3E1gCqbAF7H4k4jhDYWzIgeOioaIa/1Do3aA5HlHgfQ45AljjWSQUdc8KiNwfnuiU09J8jILzCY5E8ke802dTSlwpCJ7fDoyzNTGkBxhMJWmWyqBMBIrf5wuTvcPOLHJz3vfZvlv5jec5yyzWeXAhK4ZXxLJ5VlXrQtC+3FPVK5tzNCuEa/KMWBbypUviQSBbbN7cC15VphnLxY=
  on:
    tags: true
    repo: nicolas-van/jiko
    branch: master
